/*
 * Copyright (C) 2026  Halantar
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://gnu.org>.
 */

/*
  Built-in themes — full, hand-tuned token sets (not run through the
  theme-engine derivation, so they can be pixel-picked for best contrast).
  Custom themes (user-created) are generated by shared/theme-engine.js and
  stored separately in config.json.
*/
(function (root) {
  const BUILTIN_THEMES = {
    nebula: {
      id: "nebula",
      name: "Material You",
      builtin: true,
      category: "system",
      dimension: "2d",
      borderRadius: "24px",
      tokens: {
        "--md-primary": "#d0bcff",
        "--md-on-primary": "#381e72",
        "--md-primary-container": "#e8def8",
        "--md-on-primary-container": "#1d192b",
        "--md-secondary": "#ccc2dc",
        "--md-on-secondary": "#332d41",
        "--md-secondary-container": "#4a4458",
        "--md-on-secondary-container": "#e8def8",
        "--md-tertiary": "#efb8c8",
        "--md-on-tertiary": "#492532",
        "--md-tertiary-container": "#633b48",
        "--md-on-tertiary-container": "#ffd8e4",
        "--md-error": "#ffb4ab",
        "--md-on-error": "#690005",
        "--md-error-container": "#93000a",
        "--md-on-error-container": "#ffdad6",
        "--md-surface-dim": "#141218",
        "--md-surface": "#141218",
        "--md-surface-bright": "#3b383e",
        "--md-surface-container-lowest": "#0f0d13",
        "--md-surface-container-low": "#1d1b20",
        "--md-surface-container": "#211f26",
        "--md-surface-container-high": "#2b2930",
        "--md-surface-container-highest": "#36343b",
        "--md-on-surface": "#e6e1e5",
        "--md-on-surface-variant": "#cac4d0",
        "--md-outline": "#938f96",
        "--md-outline-variant": "#49454f",
        "--font-display": '"Manrope", "Segoe UI", sans-serif',
        "--font-body": '"Manrope", "Segoe UI", sans-serif',
        "--font-mono": '"JetBrains Mono", "Consolas", monospace',
        "--panel-radius": "24px",
        "--panel-clip": "none",
        "--panel-decoration": "none",
        "--panel-glow": "0 24px 48px rgba(0,0,0,0.45)",
        "--panel-bg": "rgba(33, 31, 38, 0.82)",
        "--panel-blur": "20px",
        "--panel-border": "1px solid rgba(255, 255, 255, 0.12)",
        "--alert-enter-easing": "cubic-bezier(0.05, 0.7, 0.1, 1)",
        "--alert-enter-duration": "480ms",
      },
    },
    orbital: {
      id: "orbital",
      name: "Orbital",
      builtin: true,
      category: "system",
      dimension: "2d",
      borderRadius: "0px",
      tokens: {
        "--md-primary": "#00f0ff",
        "--md-on-primary": "#00232b",
        "--md-primary-container": "#003544",
        "--md-on-primary-container": "#baf5ff",
        "--md-secondary": "#ffaa00",
        "--md-on-secondary": "#3d2900",
        "--md-secondary-container": "#543800",
        "--md-on-secondary-container": "#ffddab",
        "--md-tertiary": "#ff3860",
        "--md-on-tertiary": "#400010",
        "--md-tertiary-container": "#63001f",
        "--md-on-tertiary-container": "#ffd9dc",
        "--md-error": "#ffb4ab",
        "--md-on-error": "#690005",
        "--md-error-container": "#93000a",
        "--md-on-error-container": "#ffdad6",
        "--md-surface-dim": "#02060a",
        "--md-surface": "#050b10",
        "--md-surface-bright": "#26414f",
        "--md-surface-container-lowest": "#020608",
        "--md-surface-container-low": "#0a141c",
        "--md-surface-container": "#0e1a24",
        "--md-surface-container-high": "#142330",
        "--md-surface-container-highest": "#1c2e3d",
        "--md-on-surface": "#dcebf5",
        "--md-on-surface-variant": "#8ab4d0",
        "--md-outline": "#4a6b80",
        "--md-outline-variant": "#1a4a55",
        "--font-display": '"Orbitron", "Segoe UI", sans-serif',
        "--font-body": '"Rajdhani", "Segoe UI", sans-serif',
        "--font-mono": '"Orbitron", "Consolas", monospace',
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "brackets4",
        "--panel-glow": "0 0 15px rgba(0,240,255,0.3), inset 0 0 30px rgba(0,240,255,0.04)",
        "--panel-bg": "rgba(8, 14, 20, 0.92)",
        "--panel-blur": "10px",
        "--panel-border": "1px solid rgba(0, 240, 255, 0.35)",
        "--alert-enter-easing": "cubic-bezier(0.175, 0.885, 0.32, 1.2)",
        "--alert-enter-duration": "350ms",
      },
    },

    pixel: {
      id: "pixel",
      name: "Pixel Perfect",
      builtin: true,
      category: "system",
      dimension: "2d",
      borderRadius: "0px",
      tokens: {
        // ShestakUI-inspired minimal dark UI: near-black neutral surfaces,
        // flat 1px borders and a muted gold accent (no arcade blue/red/gold).
        "--md-primary": "#d6b675",
        "--md-on-primary": "#3a2c0a",
        "--md-primary-container": "#4d3c16",
        "--md-on-primary-container": "#f4dc9f",
        "--md-secondary": "#a8b0a4",
        "--md-on-secondary": "#23261f",
        "--md-secondary-container": "#3a3e36",
        "--md-on-secondary-container": "#c8d2c2",
        "--md-tertiary": "#b8a98f",
        "--md-on-tertiary": "#2d2618",
        "--md-tertiary-container": "#443c2a",
        "--md-on-tertiary-container": "#dccdb0",
        "--md-error": "#e08a7e",
        "--md-on-error": "#3a120d",
        "--md-error-container": "#5a2620",
        "--md-on-error-container": "#ffd8d2",
        "--md-surface-dim": "#0b0b0c",
        "--md-surface": "#101012",
        "--md-surface-bright": "#2a2a2d",
        "--md-surface-container-lowest": "#060607",
        "--md-surface-container-low": "#151517",
        "--md-surface-container": "#19191c",
        "--md-surface-container-high": "#202024",
        "--md-surface-container-highest": "#28282c",
        "--md-on-surface": "#e6e6e6",
        "--md-on-surface-variant": "#b8b8b8",
        "--md-outline": "#8a8a8d",
        "--md-outline-variant": "#3a3a3e",
        // Pixelify Sans — thin pixel face with Cyrillic, like ShestakUI's
        // crisp party/HP bar readouts. VT323 as a terminal fallback.
        "--font-display": '"Pixelify Sans", "VT323", monospace',
        "--font-body": '"Pixelify Sans", "VT323", monospace',
        "--font-mono": '"Pixelify Sans", "VT323", monospace',
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "none",
        "--panel-glow": "0 0 0 1px rgba(214, 182, 117, 0.15)",
        "--panel-bg": "rgba(16, 16, 18, 0.95)",
        "--panel-blur": "0px",
        "--panel-border": "1px solid rgba(138, 138, 141, 0.35)",
        "--alert-enter-easing": "cubic-bezier(0.2, 0, 0, 1)",
        "--alert-enter-duration": "240ms",
      },
    },

    grimhex: {
      id: "grimhex",
      name: "Star Citizen",
      builtin: true,
      category: "starcitizen",
      dimension: "3d",
      borderRadius: "0px",
      tokens: {
        // HUD cyan (#00F0FF) — the station's terminal accent, matching Orbital.
        "--md-primary": "#00f0ff",
        "--md-on-primary": "#00232b",
        "--md-primary-container": "#003544",
        "--md-on-primary-container": "#baf5ff",

        // Amber/gold (#FFAA00) — warning lamps, industrial sensors.
        "--md-secondary": "#ffaa00",
        "--md-on-secondary": "#3d2900",
        "--md-secondary-container": "#543800",
        "--md-on-secondary-container": "#ffddab",

        // Signal pink/red (#FF3860) — alarm accents.
        "--md-tertiary": "#ff3860",
        "--md-on-tertiary": "#400010",
        "--md-tertiary-container": "#63001f",
        "--md-on-tertiary-container": "#ffd9dc",

        "--md-error": "#ffb4ab",
        "--md-on-error": "#690005",
        "--md-error-container": "#93000a",
        "--md-on-error-container": "#ffdad6",

        // Dark blue-black HUD surfaces.
        "--md-surface-dim": "#02060a",
        "--md-surface": "#050b10",
        "--md-surface-bright": "#26414f",
        "--md-surface-container-lowest": "#020608",
        "--md-surface-container-low": "#0a141c",
        "--md-surface-container": "#0e1a24",
        "--md-surface-container-high": "#142330",
        "--md-surface-container-highest": "#1c2e3d",

        "--md-on-surface": "#dcebf5",
        "--md-on-surface-variant": "#8ab4d0",
        "--md-outline": "#4a6b80",
        "--md-outline-variant": "#1a4a55",

        "--font-display": '"Orbitron", "Segoe UI", sans-serif',
        "--font-body": '"Rajdhani", "Segoe UI", sans-serif',
        "--font-mono": '"Orbitron", "Consolas", monospace',

        // HUD terminal: cyan-tinted frames, cyan neon accent, amber warnings.
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "brackets4",
        "--panel-glow": "0 0 15px rgba(0,240,255,0.3), inset 0 0 30px rgba(0,240,255,0.04)",
        "--panel-bg": "rgba(8, 14, 20, 0.92)",
        "--panel-blur": "0px",
        "--panel-border": "1px solid rgba(0, 240, 255, 0.35)",
        "--alert-enter-easing": "cubic-bezier(0.2, 0, 0, 1)",
        "--alert-enter-duration": "240ms",

        "--shape-xs": "0px",
        "--shape-sm": "0px",
        "--shape-md": "0px",
        "--shape-lg": "0px",
        "--shape-xl": "0px",
        "--shape-full": "999px",
      },
    },

    nuclear: {
      id: "nuclear",
      name: "Nuclear",
      builtin: true,
      category: "nuclear",
      dimension: "3d",
      borderRadius: "0px",
      tokens: {
        // CRT green (#39FF14) — the accent, not a full-screen tint.
        "--md-primary": "#39ff14",
        "--md-on-primary": "#062400",
        "--md-primary-container": "#167a12",
        "--md-on-primary-container": "#c9ffc0",

        // Green accent for "connected" / positive status (same green family).
        "--md-secondary": "#39ff14",
        "--md-on-secondary": "#062400",
        "--md-secondary-container": "#167a12",
        "--md-on-secondary-container": "#c9ffc0",

        // Amber (#FFB000) — pending / warning accent.
        "--md-tertiary": "#ffb000",
        "--md-on-tertiary": "#2a1a00",
        "--md-tertiary-container": "#3d2a00",
        "--md-on-tertiary-container": "#ffe2a6",

        // Critical (red, #FF3030) — errors only.
        "--md-error": "#ff3030",
        "--md-on-error": "#2e0000",
        "--md-error-container": "#4d0000",
        "--md-on-error-container": "#ffd1d1",

        // Warning (amber, #FFB000) — explicit warning token.
        "--md-warning": "#ffb000",
        "--md-on-warning": "#2a1a00",
        "--md-warning-container": "#3d2a00",
        "--md-on-warning-container": "#ffe2a6",

        // Neutral dark-metal surfaces (no green cast).
        "--md-surface-dim": "#050605",
        "--md-surface": "#0d100e",
        "--md-surface-bright": "#171a18",
        "--md-surface-container-lowest": "#020302",
        "--md-surface-container-low": "#080a09",
        "--md-surface-container": "#0d100e",
        "--md-surface-container-high": "#121514",
        "--md-surface-container-highest": "#171a18",

        // Gray text — the CRT phosphor reads as gray, not green.
        "--md-on-surface": "#a7ada8",
        "--md-on-surface-variant": "#59615b",
        "--md-outline": "#4a514c",
        "--md-outline-variant": "#242a26",

        // Terminal monospace: IBM Plex Mono as the primary face (cold-war
        // computing), JetBrains Mono as the Cyrillic-capable fallback.
        "--font-display": '"IBM Plex Mono", "JetBrains Mono", "Consolas", monospace',
        "--font-body": '"IBM Plex Mono", "JetBrains Mono", "Consolas", monospace',
        "--font-mono": '"IBM Plex Mono", "JetBrains Mono", "Consolas", monospace',

        // CRT console: flat neutral panels, a faint gray frame and a neutral
        // drop shadow — the glow lives only on bright accent elements.
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "nuclear",
        "--panel-glow": "0 8px 24px rgba(0, 0, 0, 0.5)",
        "--panel-bg": "rgba(13, 16, 14, 0.92)",
        "--panel-blur": "0px",
        "--panel-border": "1px solid rgba(167, 173, 168, 0.18)",
        "--alert-enter-easing": "steps(1, end)",
        "--alert-enter-duration": "120ms",

        "--shape-xs": "0px",
        "--shape-sm": "0px",
        "--shape-md": "0px",
        "--shape-lg": "0px",
        "--shape-xl": "0px",
        "--shape-full": "999px",
      },
    },
  };

  const api = { BUILTIN_THEMES };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  } else {
    root.BuiltinThemes = api;
  }
})(typeof window !== "undefined" ? window : globalThis);
