/*
 * Copyright (C) 2026  Halantar
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://gnu.org>.
 */

/*
  Built-in themes — full, hand-tuned token sets (not run through the
  theme-engine derivation, so they can be pixel-picked for best contrast).
  Custom themes (user-created) are generated by shared/theme-engine.js and
  stored separately in config.json.
*/
(function (root) {
  // Elite Dangerous HUD palette: signature orange cockpit readouts on a warm
  // near-black space surface. Shared verbatim by the 2D "Elite" theme and the
  // 3D "Cobra Mk II" theme so the base overlay and the 3D widgets stay in one
  // coherent look (same relationship as Orbital ↔ Star Citizen).
  const ELITE_TOKENS = {
    // HUD orange (#ff7605) — the cockpit accent.
    "--md-primary": "#ff7605",
    "--md-on-primary": "#2a1000",
    "--md-primary-container": "#b35100",
    "--md-on-primary-container": "#ffd7b0",

    // Info blue (#00d2ff) — shields, radar, friendly contacts.
    "--md-secondary": "#00d2ff",
    "--md-on-secondary": "#001f33",
    "--md-secondary-container": "#00354f",
    "--md-on-secondary-container": "#c7ecff",

    // Hostile red (#ff3b30) — alerts, hostile contacts.
    "--md-tertiary": "#ff3b30",
    "--md-on-tertiary": "#3c000a",
    "--md-tertiary-container": "#63000f",
    "--md-on-tertiary-container": "#ffd9dc",

    "--md-error": "#ffb4ab",
    "--md-on-error": "#690005",
    "--md-error-container": "#93000a",
    "--md-on-error-container": "#ffdad6",

    // Dark-space surfaces (cool blue-black).
    "--md-surface-dim": "#05080c",
    "--md-surface": "#0a0f14",
    "--md-surface-bright": "#26201a",
    "--md-surface-container-lowest": "#030303",
    "--md-surface-container-low": "#0c0c0c",
    "--md-surface-container": "#100f0e",
    "--md-surface-container-high": "#161412",
    "--md-surface-container-highest": "#1c1916",

    "--md-on-surface": "#ffb07c",
    "--md-on-surface-variant": "#bdb0a1",
    "--md-outline": "#7a6e5f",
    "--md-outline-variant": "#3a3329",

    "--font-display": '"Orbitron", "Segoe UI", sans-serif',
    "--font-body": '"Rajdhani", "Segoe UI", sans-serif',
    "--font-mono": '"Orbitron", "Consolas", monospace',

    // Angular HUD panels: four-corner brackets, orange neon accent, no blur.
    "--panel-radius": "0px",
    "--panel-clip": "none",
    "--panel-decoration": "brackets4",
    "--panel-glow": "0 0 15px rgba(255,118,5,0.28), inset 0 0 30px rgba(255,118,5,0.04)",
    "--panel-bg": "rgba(10, 8, 6, 0.92)",
    "--panel-blur": "0px",
    "--panel-border": "1px solid rgba(255, 118, 5, 0.35)",
    "--alert-enter-easing": "cubic-bezier(0.175, 0.885, 0.32, 1.2)",
    "--alert-enter-duration": "320ms",
  };

  const BUILTIN_THEMES = {
    nebula: {
      id: "nebula",
      name: "Material You",
      builtin: true,
      category: "system",
      dimension: "2d",
      family: "nebula",
      variant3d: "nebula",
      borderRadius: "24px",
      tokens: {
        "--md-primary": "#94cbf9",
        "--md-on-primary": "#0f283d",
        "--md-primary-container": "#18568b",
        "--md-on-primary-container": "#e4ebf1",
        "--md-secondary": "#aac6e3",
        "--md-on-secondary": "#1c2631",
        "--md-secondary-container": "#305174",
        "--md-on-secondary-container": "#e8ebed",
        "--md-tertiary": "#94e9f9",
        "--md-on-tertiary": "#0f363d",
        "--md-tertiary-container": "#18798b",
        "--md-on-tertiary-container": "#e4eff1",
        "--md-error": "#ffb4ab",
        "--md-on-error": "#690005",
        "--md-error-container": "#93000a",
        "--md-on-error-container": "#ffdad6",
        "--md-surface-dim": "#0b0c0e",
        "--md-surface": "#101114",
        "--md-surface-bright": "#2d3039",
        "--md-surface-container-lowest": "#070709",
        "--md-surface-container-low": "#16181d",
        "--md-surface-container": "#1b1d22",
        "--md-surface-container-high": "#24272e",
        "--md-surface-container-highest": "#2d3039",
        "--md-on-surface": "#e9eaec",
        "--md-on-surface-variant": "#c2c5cb",
        "--md-outline": "#787f91",
        "--md-outline-variant": "#3c3f49",
        "--font-display": '"Manrope", "Segoe UI", sans-serif',
        "--font-body": '"Manrope", "Segoe UI", sans-serif',
        "--font-mono": '"JetBrains Mono", "Consolas", monospace',
        "--panel-radius": "24px",
        "--panel-clip": "none",
        "--panel-decoration": "none",
        "--panel-glow": "0 24px 48px rgba(0,0,0,0.45)",
        "--panel-bg": "rgba(27, 29, 34, 0.82)",
        "--panel-blur": "20px",
        "--panel-border": "1px solid rgba(255, 255, 255, 0.12)",
        "--alert-enter-easing": "cubic-bezier(0.05, 0.7, 0.1, 1)",
        "--alert-enter-duration": "480ms",
      },
    },
    orbital: {
      id: "orbital",
      name: "Orbital",
      builtin: true,
      category: "system",
      dimension: "2d",
      family: "starcitizen",
      variant3d: "grimhex",
      borderRadius: "0px",
      tokens: {
        "--md-primary": "#00f0ff",
        "--md-on-primary": "#00232b",
        "--md-primary-container": "#003544",
        "--md-on-primary-container": "#baf5ff",
        "--md-secondary": "#ffaa00",
        "--md-on-secondary": "#3d2900",
        "--md-secondary-container": "#543800",
        "--md-on-secondary-container": "#ffddab",
        "--md-tertiary": "#ff3860",
        "--md-on-tertiary": "#400010",
        "--md-tertiary-container": "#63001f",
        "--md-on-tertiary-container": "#ffd9dc",
        "--md-error": "#ffb4ab",
        "--md-on-error": "#690005",
        "--md-error-container": "#93000a",
        "--md-on-error-container": "#ffdad6",
        "--md-surface-dim": "#02060a",
        "--md-surface": "#050b10",
        "--md-surface-bright": "#26414f",
        "--md-surface-container-lowest": "#020608",
        "--md-surface-container-low": "#0a141c",
        "--md-surface-container": "#0e1a24",
        "--md-surface-container-high": "#142330",
        "--md-surface-container-highest": "#1c2e3d",
        "--md-on-surface": "#dcebf5",
        "--md-on-surface-variant": "#8ab4d0",
        "--md-outline": "#4a6b80",
        "--md-outline-variant": "#1a4a55",
        "--font-display": '"Orbitron", "Segoe UI", sans-serif',
        "--font-body": '"Rajdhani", "Segoe UI", sans-serif',
        "--font-mono": '"Orbitron", "Consolas", monospace',
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "brackets4",
        "--panel-glow": "0 0 15px rgba(0,240,255,0.3), inset 0 0 30px rgba(0,240,255,0.04)",
        "--panel-bg": "rgba(8, 14, 20, 0.92)",
        "--panel-blur": "10px",
        "--panel-border": "1px solid rgba(0, 240, 255, 0.35)",
        "--alert-enter-easing": "cubic-bezier(0.175, 0.885, 0.32, 1.2)",
        "--alert-enter-duration": "350ms",
      },
    },

    pixel: {
      id: "pixel",
      name: "Pixel Perfect",
      builtin: true,
      category: "system",
      dimension: "2d",
      family: "pixel",
      variant3d: "pixel",
      borderRadius: "0px",
      tokens: {
        // Minimal dark UI: near-black neutral surfaces,
        // flat 1px borders and a muted gold accent (no arcade blue/red/gold).
        "--md-primary": "#d6b675",
        "--md-on-primary": "#3a2c0a",
        "--md-primary-container": "#4d3c16",
        "--md-on-primary-container": "#f4dc9f",
        "--md-secondary": "#a8b0a4",
        "--md-on-secondary": "#23261f",
        "--md-secondary-container": "#3a3e36",
        "--md-on-secondary-container": "#c8d2c2",
        "--md-tertiary": "#b8a98f",
        "--md-on-tertiary": "#2d2618",
        "--md-tertiary-container": "#443c2a",
        "--md-on-tertiary-container": "#dccdb0",
        "--md-error": "#e08a7e",
        "--md-on-error": "#3a120d",
        "--md-error-container": "#5a2620",
        "--md-on-error-container": "#ffd8d2",
        "--md-surface-dim": "#0b0b0c",
        "--md-surface": "#101012",
        "--md-surface-bright": "#2a2a2d",
        "--md-surface-container-lowest": "#060607",
        "--md-surface-container-low": "#151517",
        "--md-surface-container": "#19191c",
        "--md-surface-container-high": "#202024",
        "--md-surface-container-highest": "#28282c",
        "--md-on-surface": "#e6e6e6",
        "--md-on-surface-variant": "#b8b8b8",
        "--md-outline": "#8a8a8d",
        "--md-outline-variant": "#3a3a3e",
        // PT Sans Caption (condensed readable text) everywhere;
        // data/numbers reuse the same font, no pixel face. Chat stays on Roboto Condensed.
        "--font-display": '"PT Sans Caption", "Segoe UI", sans-serif',
        "--font-body": '"PT Sans Caption", "Segoe UI", sans-serif',
        "--font-mono": '"PT Sans Caption", "Segoe UI", sans-serif',
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "none",
        "--panel-glow": "0 0 0 1px rgba(214, 182, 117, 0.15)",
        "--panel-bg": "rgba(16, 16, 18, 0.95)",
        "--panel-blur": "0px",
        "--panel-border": "1px solid rgba(138, 138, 141, 0.35)",
        "--alert-enter-easing": "cubic-bezier(0.2, 0, 0, 1)",
        "--alert-enter-duration": "240ms",
      },
    },

    grimhex: {
      id: "grimhex",
      name: "Star Citizen",
      builtin: true,
      category: "starcitizen",
      dimension: "3d",
      family: "starcitizen",
      variant: true,
      base2d: "orbital",
      borderRadius: "0px",
      tokens: {
        // HUD cyan (#00F0FF) — the station's terminal accent, matching Orbital.
        "--md-primary": "#00f0ff",
        "--md-on-primary": "#00232b",
        "--md-primary-container": "#003544",
        "--md-on-primary-container": "#baf5ff",

        // Amber/gold (#FFAA00) — warning lamps, industrial sensors.
        "--md-secondary": "#ffaa00",
        "--md-on-secondary": "#3d2900",
        "--md-secondary-container": "#543800",
        "--md-on-secondary-container": "#ffddab",

        // Signal pink/red (#FF3860) — alarm accents.
        "--md-tertiary": "#ff3860",
        "--md-on-tertiary": "#400010",
        "--md-tertiary-container": "#63001f",
        "--md-on-tertiary-container": "#ffd9dc",

        "--md-error": "#ffb4ab",
        "--md-on-error": "#690005",
        "--md-error-container": "#93000a",
        "--md-on-error-container": "#ffdad6",

        // Dark blue-black HUD surfaces.
        "--md-surface-dim": "#02060a",
        "--md-surface": "#050b10",
        "--md-surface-bright": "#26414f",
        "--md-surface-container-lowest": "#020608",
        "--md-surface-container-low": "#0a141c",
        "--md-surface-container": "#0e1a24",
        "--md-surface-container-high": "#142330",
        "--md-surface-container-highest": "#1c2e3d",

        "--md-on-surface": "#dcebf5",
        "--md-on-surface-variant": "#8ab4d0",
        "--md-outline": "#4a6b80",
        "--md-outline-variant": "#1a4a55",

        "--font-display": '"Orbitron", "Segoe UI", sans-serif',
        "--font-body": '"Rajdhani", "Segoe UI", sans-serif',
        "--font-mono": '"Orbitron", "Consolas", monospace',

        // HUD terminal: cyan-tinted frames, cyan neon accent, amber warnings.
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "brackets4",
        "--panel-glow": "0 0 15px rgba(0,240,255,0.3), inset 0 0 30px rgba(0,240,255,0.04)",
        "--panel-bg": "rgba(8, 14, 20, 0.92)",
        "--panel-blur": "0px",
        "--panel-border": "1px solid rgba(0, 240, 255, 0.35)",
        "--alert-enter-easing": "cubic-bezier(0.2, 0, 0, 1)",
        "--alert-enter-duration": "240ms",

        "--shape-xs": "0px",
        "--shape-sm": "0px",
        "--shape-md": "0px",
        "--shape-lg": "0px",
        "--shape-xl": "0px",
        "--shape-full": "999px",
      },
    },

    nuclear: {
      id: "nuclear",
      name: "Nuclear",
      builtin: true,
      category: "nuclear",
      dimension: "3d",
      family: "nuclear",
      variant3d: "nuclear",
      borderRadius: "0px",
      tokens: {
        // CRT green (#39FF14) — the accent, not a full-screen tint.
        "--md-primary": "#39ff14",
        "--md-on-primary": "#062400",
        "--md-primary-container": "#167a12",
        "--md-on-primary-container": "#c9ffc0",

        // Green accent for "connected" / positive status (same green family).
        "--md-secondary": "#39ff14",
        "--md-on-secondary": "#062400",
        "--md-secondary-container": "#167a12",
        "--md-on-secondary-container": "#c9ffc0",

        // Amber (#FFB000) — pending / warning accent.
        "--md-tertiary": "#ffb000",
        "--md-on-tertiary": "#2a1a00",
        "--md-tertiary-container": "#3d2a00",
        "--md-on-tertiary-container": "#ffe2a6",

        // Critical (red, #FF3030) — errors only.
        "--md-error": "#ff3030",
        "--md-on-error": "#2e0000",
        "--md-error-container": "#4d0000",
        "--md-on-error-container": "#ffd1d1",

        // Warning (amber, #FFB000) — explicit warning token.
        "--md-warning": "#ffb000",
        "--md-on-warning": "#2a1a00",
        "--md-warning-container": "#3d2a00",
        "--md-on-warning-container": "#ffe2a6",

        // Neutral dark-metal surfaces (no green cast).
        "--md-surface-dim": "#050605",
        "--md-surface": "#0d100e",
        "--md-surface-bright": "#171a18",
        "--md-surface-container-lowest": "#020302",
        "--md-surface-container-low": "#080a09",
        "--md-surface-container": "#0d100e",
        "--md-surface-container-high": "#121514",
        "--md-surface-container-highest": "#171a18",

        // Gray text — the CRT phosphor reads as gray, not green.
        "--md-on-surface": "#a7ada8",
        "--md-on-surface-variant": "#59615b",
        "--md-outline": "#4a514c",
        "--md-outline-variant": "#242a26",

        // Terminal monospace: IBM Plex Mono as the primary face (cold-war
        // computing), JetBrains Mono as the Cyrillic-capable fallback.
        "--font-display": '"IBM Plex Mono", "JetBrains Mono", "Consolas", monospace',
        "--font-body": '"IBM Plex Mono", "JetBrains Mono", "Consolas", monospace',
        "--font-mono": '"IBM Plex Mono", "JetBrains Mono", "Consolas", monospace',

        // CRT console: flat neutral panels, a faint gray frame and a neutral
        // drop shadow — the glow lives only on bright accent elements.
        "--panel-radius": "0px",
        "--panel-clip": "none",
        "--panel-decoration": "nuclear",
        "--panel-glow": "0 8px 24px rgba(0, 0, 0, 0.5)",
        "--panel-bg": "rgba(13, 16, 14, 0.92)",
        "--panel-blur": "0px",
        "--panel-border": "1px solid rgba(167, 173, 168, 0.18)",
        "--alert-enter-easing": "steps(1, end)",
        "--alert-enter-duration": "120ms",

        "--shape-xs": "0px",
        "--shape-sm": "0px",
        "--shape-md": "0px",
        "--shape-lg": "0px",
        "--shape-xl": "0px",
        "--shape-full": "999px",
      },
    },

    elite: {
      id: "elite",
      name: "Elite",
      builtin: true,
      category: "system",
      dimension: "2d",
      family: "elite",
      variant3d: "cobra-mk2",
      borderRadius: "0px",
      tokens: ELITE_TOKENS,
    },

    "cobra-mk2": {
      id: "cobra-mk2",
      name: "Cobra Mk II",
      builtin: true,
      category: "elite",
      dimension: "3d",
      family: "elite",
      variant: true,
      base2d: "elite",
      borderRadius: "0px",
      tokens: {
        ...ELITE_TOKENS,
        "--shape-xs": "0px",
        "--shape-sm": "0px",
        "--shape-md": "0px",
        "--shape-lg": "0px",
        "--shape-xl": "0px",
        "--shape-full": "999px",
      },
    },
  };

  const api = { BUILTIN_THEMES };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  } else {
    root.BuiltinThemes = api;
  }
})(typeof window !== "undefined" ? window : globalThis);
